### ISSUE TITLE
SDK catches every window.error

### ISSUE THREAD

**Issue by Newbie012** [plivo/Plivo-Browser-SDK-v2#160]
Currently, the SDK catches every error that occurs in the window (`window.onerror`):

```ts
/**
 * Prepare summary event when browser tab is about to close
 * @returns Summary event
 */
export const setErrorCollector = () => {
  window.onerror = (message) => {
    Plivo.log.error(`${LOGCAT.CRASH} | ${message} |`, new Error().stack);
  };
};
```

This function is triggered in the constructor of `Plivo` without any flag.

1. It completely overrides the original `window.onerror` which doesn't make any sense.
2. It catches and reports errors that aren't related to the SDK.

**Comment by huzaif-plivo** [comment]
@Newbie012 Thank you for notifying us. We have addressed this issue in our latest beta release, 2.2.12-beta.0. We have introduced a new flag called `captureSDKcrashOnly`. When set to `true`, this flag captures only crashes related to the SDK. Defaults to `false`.
cc - @sanyamjain-plivo
